version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-certbot
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/certbot.conf:/etc/nginx/conf.d/certbot.conf
      - /var/www/certbot:/var/www/certbot
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    command: >
      certonly --webroot --webroot-path=/var/www/certbot --email duyduysysy@gmail.com --agree-tos --non-interactive --expand --domains lucky-donation.kingofshiba.xyz
