# Generated by Django 4.2.17 on 2024-12-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_app", "0002_hederauser_remove_userprofile_wallet_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hederauser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="hederauser",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
