# Generated by Django 4.2.17 on 2024-12-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donation_app", "0005_userprofile_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DonationHistory",
        ),
    ]
