# Generated by Django 4.2.17 on 2024-12-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_app", "0007_campaign_approved_by_admin_campaign_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="onchain_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
