# Generated by Django 4.2.17 on 2024-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_app", "0008_campaign_onchain_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PUBLISHED", "Published"),
                    ("CLOSED", "Closed"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
