# Generated by Django 4.2.17 on 2024-12-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_app", "0009_alter_campaign_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastIndexCrawl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
