# Generated by Django 4.2.17 on 2024-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_app", "0010_lastindexcrawl"),
    ]

    operations = [
        migrations.AddField(
            model_name="lastindexcrawl",
            name="start_at",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
