# Generated by Django 4.2.17 on 2024-12-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_app", "0011_lastindexcrawl_start_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lastindexcrawl",
            name="start_at",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lastindexcrawl",
            name="value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
