# Generated by Django 4.2.17 on 2024-12-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_app", "0012_alter_lastindexcrawl_start_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.UniqueConstraint(
                fields=("campaign", "user", "transaction_hash"),
                name="unique_campaign_user_transaction",
            ),
        ),
    ]
