# Generated by Django 4.2.17 on 2024-12-07 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donation_app", "0014_alter_campaign_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="decimal",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="donation_app.campaigntype",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="image",
            field=models.URLField(
                blank=True, default="https://placehold.co/150x150", null=True
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="donation_app.token"
            ),
        ),
    ]
