# Generated by Django 4.2.17 on 2024-12-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_app", "0015_token_decimal_alter_campaign_campaign_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hederauser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hederauser",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hederauser",
            name="image",
            field=models.URLField(
                blank=True, default="https://placehold.co/150x150", null=True
            ),
        ),
        migrations.AddField(
            model_name="hederauser",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hederauser",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
