# Generated by Django 4.2.17 on 2024-12-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "donation_app",
            "0016_hederauser_bio_hederauser_facebook_hederauser_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="transaction_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
