# Generated by Django 4.2.17 on 2024-12-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_app", "0017_campaign_transaction_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="percentage_completed",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
