# Generated by Django 4.2.17 on 2024-12-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_app", "0018_alter_campaign_percentage_completed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="transaction_hash",
            new_name="transaction_hash_create",
        ),
        migrations.AddField(
            model_name="campaign",
            name="transaction_hash_withdrawn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lastindexcrawl",
            name="key",
            field=models.CharField(default="crawl_onchain", max_length=255),
        ),
    ]
