# Generated by Django 4.2.17 on 2024-12-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "donation_app",
            "0019_rename_transaction_hash_campaign_transaction_hash_create_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="image",
            field=models.CharField(
                blank=True, default="https://placehold.co/150x150", null=True
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="project_url",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="video_link",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hederauser",
            name="facebook",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hederauser",
            name="image",
            field=models.CharField(
                blank=True, default="https://placehold.co/150x150", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hederauser",
            name="twitter",
            field=models.CharField(blank=True, null=True),
        ),
    ]
