# Generated by Django 4.2.17 on 2024-12-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0020_alter_campaign_image_alter_campaign_project_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='account_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
