# Generated by Django 4.2.17 on 2024-12-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0021_token_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='percentage_completed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
    ]
