/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  HipTokenCreator,
  HipTokenCreatorInterface,
} from "../../../../../contracts/hedera/development/HipTokenCreator.sol/HipTokenCreator";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "initialSupply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "decimals",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "autoRenewPeriod",
        type: "uint32",
      },
    ],
    name: "createFungible",
    outputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610264908161001c8239f35b600080fdfe6080604052600436101561001257600080fd5b6000803560e01c63a491b48a1461002857600080fd5b60031960a03682011261013b5767ffffffffffffffff60043581811161015657610056903690600401610192565b906024359081116101565761006f903690600401610192565b916084359163ffffffff8316809303610152576020926100be6100af9360405196879586956376f786b560e01b875260a0600488015260a48701906101ee565b918583030160248601526101ee565b906044356044840152606435606484015260848301520381346101675af19081156101475782916100fe575b6040516001600160a01b0383168152602090f35b90506020813d821161013f575b816101186020938361015a565b8101031261013b57516001600160a01b038116810361013b5760209150386100ea565b5080fd5b3d915061010b565b6040513d84823e3d90fd5b8480fd5b8380fd5b90601f8019910116810190811067ffffffffffffffff82111761017c57604052565b634e487b7160e01b600052604160045260246000fd5b81601f820112156101e95780359067ffffffffffffffff821161017c57604051926101c7601f8401601f19166020018561015a565b828452602083830101116101e957816000926020809301838601378301015290565b600080fd5b919082519283825260005b84811061021a575050826000602080949584010152601f8019910116010190565b6020818301810151848301820152016101f956fea2646970667358221220ba2c320ef6c0e5c021831d38ce5ce733a1b4943bcf965b2e01e2ce7be7cd102764736f6c63430008120033";

type HipTokenCreatorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HipTokenCreatorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class HipTokenCreator__factory extends ContractFactory {
  constructor(...args: HipTokenCreatorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      HipTokenCreator & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): HipTokenCreator__factory {
    return super.connect(runner) as HipTokenCreator__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HipTokenCreatorInterface {
    return new Interface(_abi) as HipTokenCreatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): HipTokenCreator {
    return new Contract(address, _abi, runner) as unknown as HipTokenCreator;
  }
}
