/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHederaTokenService,
  IHederaTokenServiceInterface,
} from "../../../../../contracts/hedera/development/HipTokenCreator.sol/IHederaTokenService";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "initialSupply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "decimals",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "autoRenewPeriod",
        type: "uint32",
      },
    ],
    name: "createFungibleToken",
    outputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IHederaTokenService__factory {
  static readonly abi = _abi;
  static createInterface(): IHederaTokenServiceInterface {
    return new Interface(_abi) as IHederaTokenServiceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHederaTokenService {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IHederaTokenService;
  }
}
