/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as development from "./development";
export type { development };
import type * as system from "./system";
export type { system };
